[package]
edition = "2021"
name = "logic"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dictionary = {path = "../dictionary"}
smallvec = {version = "1.8.0", features = ["const_generics", "union"]}
